name: sync vers tig (SSH)

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITEA_SSH_KEY }}

      - name: Push to Gitea
        env:
          GITEA_URL: ${{ secrets.GITEA_URL }}
        run: |
          git remote add gitea "$GITEA_URL"
          git push gitea HEAD:main --force
